/* 'atmoscal' runs atmosphere.c and compares the ouput with one of m.sandler's
 * apd.dat files to determine a 'c' and 'sigma' that generated a close match to
 * the curve for the desired value of Vd.  An initial guess for 'c' and 'sigma'
 * is required.  The algorithm adjusts 'sigma' to match the gaussian portions
 * of the curves 1st, and then adjusts 'c' to get the required value of Vd.
 * The calibration uses the same seed for each run of atmosphere() for 
 * repeatable results.  The only change from run-to-run is the weighting.
 * r.coutts 11/92

   copyright (c) 1994 The MITRE Corporation Bedford, MA

   $Id: atmoscal.c,v 2.2 1994/07/25 18:11:46 jjb Exp $
   $Log: atmoscal.c,v $
 * Revision 2.2  1994/07/25  18:11:46  jjb
 * added Copyright notices
 *

 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <Cmdline.h>
#include <math.h>
#define	PMIN		0.8		/* defines start of gaussian portion of curves */
#define	DELTAVD		0.10	/* diff in Vd that is OK */
#define	DELTASIGMA	0.20	/* diff in Vd that is OK */
#define	VDTOCFACTOR	0.30	/* factor relative delta vd to change in c */

typedef struct CURVE { float p, db; } CURVE;

/* functions */
float getvd(char *);
void WriteCurve(char *, CURVE *, int);

static char rcsid[] = "$Id: atmoscal.c,v 2.2 1994/07/25 18:11:46 jjb Exp $";

void main(int argc, char **argv) {
	char	*atmosfile="/home/ve/rcoutts/hf/atmosphere/atmosphere";/* program */
	char	apdfile[100];		/* apd*.dat file name */
	char	statfile[100];		/* .stat file generated by atmosphere* */
	char	hstfile[100];		/* .stat file generated by atmosphere* */
	char	string[100];		/* system string */
	char	file[100];			/* file name */
	float	c = 0.0;			/* c */
	float 	sigma = 0.0;		/* sigma */
	float	vdtocfactor = VDTOCFACTOR;	/* ratio to change vd */
	float	seconds = 1.0;		/* time duration of run */
	float	samplerate = 1.0;/* sample rate */
	float	flashespersec = 100;/* flashes per second */
	float	desiredVd;			/* desired value of Vd */
	float	deltavd;			/* diff in Vd betw theoretical and sim */
	float	old_deltavd = 0.0;	/* previous value of 'deltavd' */
	float	vd;					/* Vd value */
	CURVE	apd[100];			/* apd CDF curve */
	int		napds;				/* # elems in apd[] */
	CURVE	hst[100];			/* apd CDF curve */
	int		nhsts;				/* # elems in hst[] */
	float	p;					/* probability */
	float	db;					/* dB */
	float	ptotal;				/* total accumulated p */
	int		i;					/* index */
	int		j;					/* index */
	FILE	*apdfp;				/* apd*.dat file ptr */
	FILE	*hstfp;				/* .hst file ptr */
	float	deltasigma;			/* diff betw gaussian portion of curves */
	float	deltac;				/* change in c */
	float	dbhst;				/* interpolated pt in hst[].db using apd[].p */
	float	dbtotal;			/* db diff accum in gaussian portion of curves*/
	int		ndbs;				/* # pts accum in dbtotal */
	int		seedrng;			/* atmosphere() seed */
	float	temp;				/* temporary storage */
	float	fjunk;				/* junk */


	/* print copyright notice */

	fprintf(stdout,"copyright (c) 1994 The MITRE Corporation Bedford, MA\n");

	CmdFloat("-t Time(seconds)", &seconds, cmdMan);
	CmdFloat("-s Sample_Rate(MHz)", &samplerate, cmdDef);
	CmdString("-apd apd_File_Name", apdfile, 100, cmdMan);
	CmdFloat("-f Flashes_Per_Second", &flashespersec, cmdMan);
	CmdFloat("-c", &c, cmdOpt);
	CmdFloat("-sigma", &sigma, cmdOpt);
	CmdArgs(argc, argv);
	CmdUnMan();

	/* get apd CDF data */
	if((apdfp = fopen(apdfile, "r")) == NULL) {
		printf("Error from atmoscal: apd file '%s' not opened", apdfile);
		exit(1);
	}
	/* read in to line header */
	fscanf(apdfp, "%f%f", &desiredVd, &fjunk);	/* get desired vd */
	if(c == 0.0 || sigma == 0.0) {
		fscanf(apdfp, "%f%f", &c, &sigma);		/* get c and sigma in file */
		sigma = pow(10.0, sigma/20.0);				/* convert to dB */
	} else {
		fscanf(apdfp, "%f%f", &fjunk, &fjunk);	/* ignore c and sigma in file */
	}
	/* print to screen */
	printf(" desired Vd:%.3f\n", desiredVd);
	printf("    c guess:%.3f\n", c);
	printf("sigma guess:%.3f\n", sigma);
	/* read in values */
	napds = 0;
	while(fscanf(apdfp, "%f%f", &apd[napds].db, &apd[napds].p) != EOF) napds++;
	fclose(apdfp);					/* close .apd file */
	/* write .apd curve to file */
	WriteCurve("apd.cdf", apd, napds);
	seedrng = GetSeed();		/* get random number seed */

	/* run 'atmosphere' until curve approximate theoretical */
	do {
		/* run atmosphere* */
		sprintf(string, "%s -t %.3f -cs -s %f -c %.3f -sigma %.3f -f %.3f -S %d"
			, atmosfile, seconds, samplerate, c, sigma, flashespersec, seedrng);
		printf("'%s'\n", string);
		system(string);
		/* read Vd from .stat file */
		sprintf(file, "atm%d", (int)rint(flashespersec));
		strcpy(statfile, file);
		strcat(statfile, ".stat");
		vd = getvd(statfile);
		/* read .hst file and convert to a CDF */
		strcpy(hstfile, file);
		strcat(hstfile, ".hst");
		if((hstfp = fopen(hstfile, "r")) == NULL) {
			printf("Error from atmoscal: histogram file '%s' not opened",
				hstfile);
			exit(1);
		}
		fscanf(hstfp, "%f%f", &db, &ptotal);	/* read in overflow */
		nhsts = 0;
		while(fscanf(hstfp, "%f%f", &db, &p) != EOF) {
			ptotal += p;				/* accumulate db for CDF */
			hst[nhsts].db = db;			/* get probability */
			hst[nhsts++].p = ptotal;	/* accumulate db */
		}
		fclose(hstfp);					/* close .hst file */
		/* normalize CDF to probability */
		for(i = 0; i < nhsts; i++) {
			hst[i].p /= ptotal;			/* normalize */
			hst[i].p = 1.0-hst[i].p;	/* create inv CDF */
		}
		/* now flip inv CDF so starts at low prob */
		for(i = 0; i < nhsts/2; i++) {
			/* flip .p */
			temp = hst[i].p;			/* save */
			hst[i].p = hst[nhsts-1-i].p;/* swap */
			hst[nhsts-1-i].p = temp;	/* complete swap */
			/* flip .db */
			temp = hst[i].db;				/* save */
			hst[i].db = hst[nhsts-1-i].db;	/* swap */
			hst[nhsts-1-i].db = temp;		/* complete swap */
		}
		/* overwrite end points with extremes to facilitate interpolation.
		 * this is kindof a shitty fix */
		hst[0].db = 1000;					/* exteme end of curve... */
		hst[0].p = 0.0;						/* has zero probability */
		hst[nhsts-1].db = -1000;			/* other extreme... */
		hst[nhsts-1].p = 1.0;				/* has high probability */
		/* write .hst curve to file */
		WriteCurve("hst.cdf", hst, nhsts);
		/* goto start of gaussian portion of curve */
		i = 0;
		while(apd[i].p < PMIN) i++; /* PMIN defines start of gaussian */
		dbtotal = 0.0;				/* accum diff betw curves for gaussian pts*/
		ndbs = 0;					/* # of gaussian pts */
		for(; i < napds; i++) {		/* loop thru all apds pts */
			j = 0;
			while(hst[j].p < apd[i].p && j < nhsts) j++;
			if(j == nhsts) {
				printf("Oh, oh... big error from atmoscal, writing '_hst.dat' "
				"and '_apd.dat' to file.  The problem is apd[%d].p = %f and "
				"could not fit into the hst curve.\n", i, apd[i].p);
				WriteCurve("_apd.cdf", apd, napds);
				WriteCurve("_hst.cdf", hst, nhsts);
				exit(1);
			}
			if(j == 0) {
				printf("Error from atmoscal: j = 0");
				exit(1);
			}
			/* interpolate db value from hst[].db */
			dbhst = hst[j-1].db+((hst[j].db-hst[j-1].db)*
				(apd[i].p-hst[j-1].p)/(hst[j].p-hst[j-1].p));
			dbtotal += dbhst-apd[i].db;		/* accum diff betw curves */
			ndbs++;							/* # dbtotals */
		}
		deltasigma = dbtotal/ndbs;	/* diff betw gaussian portion of curves */
		deltavd = vd-desiredVd;		/* get delta Vd */
		/* check if another pass must be made */
		if(fabs(deltasigma) > DELTASIGMA || fabs(deltavd) > DELTAVD) {
			/* remove .stat and .hst files */
			sprintf(string, "rm -f %s %s\n", hstfile, statfile);
			system(string);					/* output string to UNIX */
		}
		/* if sigma must be adjusted, adjust and run again.  Only adjust c
		 * if sigma is OK to prevent flip-flopping of two params.
		 */
		if(fabs(deltasigma) > DELTASIGMA) {
			printf("                                     deltasigma(dB):%.3f\n",
				deltasigma);
			/* convert deltasigma to voltage */
			deltasigma = pow(10.0, deltasigma/20.0);
			sigma /= deltasigma;		/* adj sigma by offset */
		} else if(fabs(deltavd) > DELTAVD) {
			printf("Vd:%.3f                                     deltavd:%.3f\n",
				vd, deltavd);
			if((deltavd > 0 && old_deltavd < 0) ||	/* check if vdtocfactor.. */
			   (deltavd < 0 && old_deltavd > 0))	/* ..was too big */
			{
				vdtocfactor /= 2.0;					/* cut in 1/2 (too big) */
				printf("vdtocfactor adjusted to %.3f\n", vdtocfactor);
			}
			deltac = vdtocfactor*deltavd;		/* get change in c */
			c += deltac;						/* adj c */
			old_deltavd = deltavd;				/* save previous deltavd */
		} else {	/* deltas ok, print some stuff out */
			printf("\n\n");
			sprintf(string, "mv %s atm_vd%df%d.hst", hstfile, (int)desiredVd,
				(int)rint(flashespersec));
			system(string);
			sprintf(string, "mv %s atm_vd%df%d.stat", statfile, (int)desiredVd,
				(int)rint(flashespersec));
			system(string);
			printf("CALIBRATION COMPLETE: deltavd:%.3f deltasigma:%.3f\n",
				fabs(deltavd), fabs(deltasigma));
		}
		printf("\n\n");
	} while(fabs(deltavd) > DELTAVD || fabs(deltasigma) > DELTASIGMA);
}

/* write curve to file */
void WriteCurve(char *filename, CURVE curve[], int npts) {
	FILE	*fp;
	int		i;
	if((fp = fopen(filename, "w")) == NULL) {
		printf("Error from atmoscal: '%s' not opened", filename);
		exit(1);
	}
	for(i = 0; i < npts; i++) fprintf(fp, "%f\t%f\n", curve[i].p, curve[i].db);
	fclose(fp);
}
	
/* read in Vd from .stat file */
float getvd(char *filename) {
	char	string[100];	/* line of file */
	char	*c;				/* ptr within string[] */
	float	out;			/* output */
	FILE	*fp;			/* */

	if((fp = fopen(filename, "r")) == NULL) {
		printf("Error from atmoscal(): statistics file `%s' not opened\n",
			filename);
		exit(1);
	}
	while(fgets(string, 100, fp) != NULL) {
		if(c = strstr(string, "Vd:")) {
			sscanf(c+3, "%f", &out);
		}
	}
	fclose(fp);
	return out;
}
